### ISSUE TITLE
Compatibility with SLEAP data?

### ISSUE THREAD

**Issue by rosskempner** [BelloneLab/lisbet#8]
Hi, I have SLEAP data that I want to use that is with two animals with 6 points for each animal. How would I set up a dataset to work with your code? So far what I have made is not going through with the "Model training using self-supervised learning" section which is what I need to do to create a new model with these new keypoints. Here is the error message with the code I ran on the top

```
 betman train_model \
>    -v \
>    --task_ids=nwp,smp,vsp,dmp \  # Use all the available self-supervised tasks
t64x8-Yuan-csv \
   --seed=1234 \
   --epochs=100 \
   --emb_dim=64 \
   --num_layers=8 \
   --num_heads=8 \
   --hidden_dim=256 \
   --train_sample=0.05 \
   --save_history \
   datasets/csv
```

> 
> Loading generic DLC dataset: 0it [00:00, ?it/s]
> INFO:root:Training set size =  0 videos
> INFO:root:Assigning records from dataset no. 0 to task nwp
> INFO:root:Final training set size = 0
> INFO:root:Final test set size = 0
> INFO:root:Final dev set size = 0
> INFO:root:Assigning records from dataset no. 0 to task smp
> INFO:root:Final training set size = 0
> INFO:root:Final test set size = 0
> INFO:root:Final dev set size = 0
> INFO:root:Assigning records from dataset no. 0 to task vsp
> INFO:root:Final training set size = 0
> INFO:root:Final test set size = 0
> INFO:root:Final dev set size = 0
> INFO:root:Assigning records from dataset no. 0 to task dmp
> INFO:root:Final training set size = 0
> INFO:root:Final test set size = 0
> INFO:root:Final dev set size = 0
> Traceback (most recent call last):
>   File "/home/evan/anaconda3/envs/social_foraging/bin/betman", line 8, in <module>
>     sys.exit(main())
>   File "/home/evan/anaconda3/envs/social_foraging/lib/python3.10/site-packages/lisbet/cli.py", line 441, in main
>     lazy_load_handler(
>   File "/home/evan/anaconda3/envs/social_foraging/lib/python3.10/site-packages/lisbet/cli.py", line 98, in lazy_load_handler
>     handler(**filtered_args)
>   File "/home/evan/anaconda3/envs/social_foraging/lib/python3.10/site-packages/lisbet/training.py", line 669, in train
>     trainer = Trainer(locals())
>   File "/home/evan/anaconda3/envs/social_foraging/lib/python3.10/site-packages/lisbet/training.py", line 91, in __init__
>     self.bp_dim = self.train_rec[self.task_ids[0]][0][1]["keypoints"].shape[1]
> IndexError: list index out of range
> (social_foraging) ~/LISBET-social-foraging$    --data_format=maDLC \
> >    --run_id=lisbet64x8-Yuan-csv \
> >    --seed=1234 \
> >    --epochs=100 \
> >    --emb_dim=64 \
> >    --num_layers=8 \
> >    --num_heads=8 \
> >    --hidden_dim=256 \
> >    --train_sample=0.05 \
> >    --save_history \
> >    datasets/csv
> bash: --data_format=maDLC: command not found

Now here is a snapshot of what one of my tracking.csv files that I used looks like: 
<img width="908" alt="Screenshot 2024-12-04 at 3 22 34 PM" src="https://github.com/user-attachments/assets/c17949d8-2cb9-4a4d-8584-f1bf2e2f9f13">

And here is my directory structure: 
<img width="216" alt="Screenshot 2024-12-04 at 3 25 43 PM" src="https://github.com/user-attachments/assets/9c2616d3-7798-4856-a8e5-e8031ca53bb5">

**Comment by talmo** [comment]
Thanks @gchindemi! We were about to do this ourselves for testing this out. If it helps, [`sleap-io`](https://io.sleap.ai) makes it easy to work with SLP files.

I'd also recommend [`movement`](https://movement.neuroinformatics.dev/) as an I/O layer that's even more general.

**Comment by rosskempner** [comment]
Yes would love to give it a try! Thanks @gchindemi!

**Comment by gchindemi** [comment]
Actually the local version I was mentioning is using `movement` (and so `sleap-io`)!
I did not push it yet because I wanted to make sure that `xarray` would not cause any issues.
I am almost done with that and I expect to push the branch this week.

**Comment by rosskempner** [comment]
Thanks! Looking forward to testing it out.

**Comment by gchindemi** [comment]
Hey @rosskempner, I just pushed a feature branch with (experimental) SLEAP support.
I still need to clean up several things, but it should be enough to start.

**Comment by rosskempner** [comment]
Hey @gchindemi . Thanks! How do you recommend I use it? What parameters do I have to use in the high level interface to get it working with SLEAP. I want to create embeddings for SLEAP data using self-supervised learning and also use it for the discovery and hypothesis driven mode. Which of these functions are available and what do I need to know to utilize them as far as parameters in the different commands go?

**Comment by gchindemi** [comment]
Dear @rosskempner, sorry for the late reply. In principle using SLEAP or DLC tracking should not matter, you can simply follow the documentation as usual. I am about to merge the `movement` branch into main and release a new LISBET version with several improvements. Please feel free to create a new issue if you encounter any problems while using SLEAP.
